### ISSUE TITLE
Resource 'Contribute\Controller\Admin\Contribute' not found

### ISSUE THREAD

**Issue by elindberg11** [Daniel-KM/Omeka-S-module-Contribute#1]
After creating token, returning to resource page generates this error.

Zend\Permissions\Acl\Exception\InvalidArgumentException: Resource 'Contribute\Controller\Admin\Contribute' not found in /home/gainings/public_html/vendor/zendframework/zend-permissions-acl/src/Acl.php:291
Stack trace:
#0 /home/gainings/public_html/vendor/zendframework/zend-permissions-acl/src/Acl.php(737): Zend\Permissions\Acl\Acl->getResource('Contribute\\Cont...')
#1 /home/gainings/public_html/application/src/Permissions/Acl.php(87): Zend\Permissions\Acl\Acl->isAllowed(Object(Zend\Permissions\Acl\Role\GenericRole), 'Contribute\\Cont...', 'expire-tokens')
#2 /home/gainings/public_html/application/src/View/Helper/UserIsAllowed.php(36): Omeka\Permissions\Acl->userIsAllowed('Contribute\\Cont...', 'expire-tokens')
#3 [internal function]: Omeka\View\Helper\UserIsAllowed->__invoke('Contribute\\Cont...', 'expire-tokens')
#4 /home/gainings/public_html/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Omeka\View\Helper\UserIsAllowed), Array)
#5 /home/gainings/public_html/modules/Contribute/view/common/admin/contribute-list.phtml(37): Zend\View\Renderer\PhpRenderer->__call('userIsAllowed', Array)
#6 /home/gainings/public_html/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/home/gainings/...')
#7 /home/gainings/public_html/vendor/zendframework/zend-view/src/Helper/Partial.php(62): Zend\View\Renderer\PhpRenderer->render(NULL, Array)
#8 [internal function]: Zend\View\Helper\Partial->__invoke('common/admin/co...', Array)
#9 /home/gainings/public_html/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Zend\View\Helper\Partial), Array)
#10 /home/gainings/public_html/modules/Contribute/Module.php(406): Zend\View\Renderer\PhpRenderer->__call('partial', Array)
#11 /home/gainings/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Contribute\Module->displayTab(Object(Zend\EventManager\Event))
#12 /home/gainings/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#13 /home/gainings/public_html/application/src/View/Helper/Trigger.php(61): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#14 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.after')
#15 /home/gainings/public_html/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#16 /home/gainings/public_html/modules/Next/view/omeka/admin/item/show.phtml(95): Zend\View\Renderer\PhpRenderer->__call('trigger', Array)
#17 /home/gainings/public_html/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/home/gainings/...')
#18 /home/gainings/public_html/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#19 /home/gainings/public_html/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#20 /home/gainings/public_html/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#21 /home/gainings/public_html/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#22 /home/gainings/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#23 /home/gainings/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#24 /home/gainings/public_html/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#25 /home/gainings/public_html/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#26 /home/gainings/public_html/index.php(21): Zend\Mvc\Application->run()
#27 {main}

**Comment by Daniel-KM** [comment]
Thanks, it should be fixed in master version.

**Comment by elindberg11** [comment]
Thank you very much!
